# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Update Go SDK
        run: go get github.com/fastly/compute-sdk-go@latest

      - name: Deploy to Compute@Edge
        uses: fastly/compute-actions@v5
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_KEY }}
        with:
          token: ${{ secrets.FASTLY_API_KEY }}
      - run: fastly compute publish --token ${{ secrets.FASTLY_API_KEY }}
